/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controla.Clientes;
import Controla.Locadora;
import javax.swing.JOptionPane;

/**
 *
 * @author Davi Tenorio
 */
public class TelaCheckIn extends javax.swing.JFrame {
  Clientes clientes;
  TelaMenu menu;
  Locadora l ;
  TelaCheckIn tci ;
  TelaCheckOut tco;  
  TelaAluguel ta ;
  TelaCadastrar tc;
  
  /**
     * Creates new form TelaCheckIn
     * @param menu
     */
    public TelaCheckIn(TelaMenu menu) {
       this.menu = menu;  
       this.ta = new TelaAluguel(this);
       this.clientes = this.menu.getTc().getClientes();
       initComponents();
    }

    public TelaMenu getMenu() {
        return menu;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextVerificaNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextVerificaCPF = new javax.swing.JTextField();
        jButtonLOGIN = new javax.swing.JButton();
        jVOLTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NOME");

        jTextVerificaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVerificaNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        jButtonLOGIN.setText("LOGIN");
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });

        jVOLTAR.setText("VOLTAR");
        jVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVOLTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jVOLTAR)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextVerificaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextVerificaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLOGIN)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextVerificaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextVerificaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLOGIN)
                    .addComponent(jVOLTAR))
                .addGap(68, 68, 68))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVOLTARActionPerformed
        this.setVisible(false); 
        //this.dispose();       
    }//GEN-LAST:event_jVOLTARActionPerformed

    private void jTextVerificaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVerificaNomeActionPerformed
     
    }//GEN-LAST:event_jTextVerificaNomeActionPerformed

    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed
        
    clientes.VerificaCadastro(jTextVerificaNome.getText(),jTextVerificaCPF.getText());
         if (clientes.getOp() == 1) {
             this.setVisible(false); 
            JOptionPane.showMessageDialog(null, "Bem-Vindo");
            this.ta.setVisible(true);  
          
           
        }else if (clientes.getOp() == 0) {
            JOptionPane.showMessageDialog(null, "Usuário inválido");
            
        }     
          
         
    }//GEN-LAST:event_jButtonLOGINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextVerificaCPF;
    private javax.swing.JTextField jTextVerificaNome;
    private javax.swing.JButton jVOLTAR;
    // End of variables declaration//GEN-END:variables
}
