/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controla.Clientes;
import Controla.Locadora;
import javax.swing.JOptionPane;
/**
 *
 * @author Davi Tenorio
 */
public class TelaAluguel extends javax.swing.JFrame {
  Clientes clientes;
  TelaMenu menu;
  Locadora l ;
  TelaCheckIn tc ;
  TelaCheckOut tco;  
  TelaAluguel ta;
  TelaEscolhaCarro tec;
    /**
     * Creates new form TelaAluguel
     */
    public TelaAluguel(TelaCheckIn menu) {
       this.tc = menu;
       this.tec = new TelaEscolhaCarro(this);
       // this.clientes = this.menu.getTc().getClientes();
        this.tc.menu.getTc().getClientes();
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPLANO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CheckPlano1 = new javax.swing.JCheckBox();
        CheckPlano2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextNdias = new javax.swing.JTextField();
        CheckPlano3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        valorTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SELECIONE ");

        jPLANO.setText("PLANO");

        jLabel3.setText("SEGURO");

        CheckPlano1.setText("Básico");
        CheckPlano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPlano1ActionPerformed(evt);
            }
        });

        CheckPlano2.setText("Intermediario");
        CheckPlano2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPlano2ActionPerformed(evt);
            }
        });

        jLabel2.setText("DIAS");

        jTextNdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNdiasActionPerformed(evt);
            }
        });

        CheckPlano3.setText("Luxo");
        CheckPlano3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPlano3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("SIM/NÃO");

        jButton1.setText("CONTINUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        valorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTotalActionPerformed(evt);
            }
        });

        jLabel4.setText("VALOR TOTAL");

        jButton3.setText("CALCULAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("R$ 100");

        jLabel6.setText("R$ 200");

        jLabel7.setText("R$ 300");

        jLabel8.setText("DIARIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jPLANO)
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))))
                                    .addComponent(jButton2))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jTextNdias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(50, 50, 50)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(CheckPlano1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CheckPlano2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CheckPlano3)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPLANO)
                            .addComponent(CheckPlano1)
                            .addComponent(CheckPlano2)
                            .addComponent(CheckPlano3))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addComponent(jCheckBox4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CheckPlano1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPlano1ActionPerformed
        if (CheckPlano1.isSelected()) {
            CheckPlano2.setSelected(false);
            CheckPlano3.setSelected(false);
        }
    }//GEN-LAST:event_CheckPlano1ActionPerformed

    private void CheckPlano2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPlano2ActionPerformed
        if (CheckPlano2.isSelected()) {
            CheckPlano1.setSelected(false);
            CheckPlano3.setSelected(false);
        }
    }//GEN-LAST:event_CheckPlano2ActionPerformed

    private void CheckPlano3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPlano3ActionPerformed
        if (CheckPlano3.isSelected()) {
            CheckPlano1.setSelected(false);
            CheckPlano2.setSelected(false);
        }
    }//GEN-LAST:event_CheckPlano3ActionPerformed

    private void valorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalActionPerformed

    }//GEN-LAST:event_valorTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // new TelaEscolhaCarro().setVisible(true);    
      if(CheckPlano3.isSelected() || CheckPlano2.isSelected() || CheckPlano1.isSelected()){
          if(jTextNdias.getText()!=null){
      this.tec.setVisible(true);}
          this.setVisible(false);
      }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int ndias = Integer.parseInt(jTextNdias.getText());

        if (CheckPlano1.isSelected() && jCheckBox4.isSelected()) {
            int valorDiaria = 100;
            int VS = (valorDiaria / 2)* ndias;
            int VT = valorDiaria * ndias + VS;
            valorTotal.setText("" + VT);
        }else if (CheckPlano1.isSelected()) {
            int valorDiaria = 100;
            int VT = valorDiaria * ndias;
            valorTotal.setText("" + VT);
        } 

        if (CheckPlano2.isSelected() && jCheckBox4.isSelected()) {
            int valorDiaria = 200;
            int VS = (valorDiaria / 2)* ndias;
            int VT = valorDiaria * ndias + VS;
            valorTotal.setText("" + VT);
        }else if (CheckPlano2.isSelected()) {
            int valorDiaria = 200;
            int VT = valorDiaria * ndias;
            valorTotal.setText("" + VT);
        }

        if (CheckPlano3.isSelected() && jCheckBox4.isSelected()) {
            int valorDiaria = 300;
            int VS = (valorDiaria / 2)* ndias;
            int VT = valorDiaria * ndias + VS;
            valorTotal.setText("" + VT);
        } else if (CheckPlano3.isSelected()) {
            int valorDiaria = 300;
            int VT = valorDiaria * ndias;
            valorTotal.setText("" + VT);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextNdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNdiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNdiasActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckPlano1;
    private javax.swing.JCheckBox CheckPlano2;
    private javax.swing.JCheckBox CheckPlano3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jPLANO;
    private javax.swing.JTextField jTextNdias;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
